"""Batch image describer for the Civ VI Access mod.

Runs a folder of game-art images through Gemini and produces short +
long visual descriptions suitable for the screen-reader. Output is a
JSON file (canonical, easy to diff and re-run) and a Civ VI LOC XML
file the mod registers via UpdateText so descriptions are
Locale.Lookup-able and translator-friendly via Crowdin.

Usage:
    GEMINI_API_KEY=... python describe.py \
        --images path/to/wonder/portraits/ \
        --prompt prompts/natural-wonders.txt \
        --output-json output/natural-wonders.json \
        --output-xml  ../../CivViAccessMod/Assets/Text/en_US/NaturalWonderDescriptions.xml \
        --loc-prefix LOC_CIVVIACCESS_NW

Filename convention: each image file's name (without extension) becomes
the LOC key suffix. With `--loc-prefix LOC_CIVVIACCESS_NW` and image
`FEATURE_BERMUDA_TRIANGLE.png`, the script emits two LOC rows:
  LOC_CIVVIACCESS_NW_FEATURE_BERMUDA_TRIANGLE_SHORT
  LOC_CIVVIACCESS_NW_FEATURE_BERMUDA_TRIANGLE_LONG
The mod's picker companion looks these up at speech time. Translators
treat them as ordinary LOC strings.

Resume: if the output JSON already has an entry for a given key, that
key is skipped. Delete the entry from the JSON to re-describe it.
"""

import argparse
import json
import os
import sys
import time
from pathlib import Path
from xml.sax.saxutils import escape as xml_escape


SUPPORTED_EXTENSIONS = {".png", ".jpg", ".jpeg", ".webp"}


def load_existing(path: Path) -> dict:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        print(f"WARN: existing output {path} is malformed JSON ({e}); starting fresh.")
        return {}


def write_json(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(data, indent=2, sort_keys=True, ensure_ascii=False),
        encoding="utf-8",
    )


def write_xml(path: Path, data: dict, loc_prefix: str, source_note: str) -> None:
    """Emit a Civ VI BaseGameText XML — one Row per LOC tag.

    Each image stem produces two rows, suffixed _SHORT and _LONG. The
    mod registers this file via <UpdateText> in CivViAccessMod.modinfo
    so the engine's BaseGameText table picks up the tags and
    Locale.Lookup just works.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    prefix = loc_prefix.rstrip("_")
    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        "<!--",
        "    " + source_note,
        "    Generated by tools/wonder-describer/describe.py.",
        "    Edit the prompt and re-run rather than editing by hand;",
        "    translation files (other languages) ARE hand-edited.",
        "-->",
        "<GameData>",
        "    <BaseGameText>",
    ]
    for stem in sorted(data.keys()):
        entry = data[stem]
        short = entry.get("short", "")
        long_ = entry.get("long", "")
        lines.append(f'        <Row Tag="{prefix}_{stem}_SHORT">')
        lines.append(f"            <Text>{xml_escape(short)}</Text>")
        lines.append("        </Row>")
        lines.append(f'        <Row Tag="{prefix}_{stem}_LONG">')
        lines.append(f"            <Text>{xml_escape(long_)}</Text>")
        lines.append("        </Row>")
    lines.append("    </BaseGameText>")
    lines.append("</GameData>")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def describe_one(client, model: str, prompt: str, image_path: Path) -> dict:
    """Send one image + prompt to Gemini, return parsed {short, long}."""
    from google.genai import types

    image_bytes = image_path.read_bytes()
    mime = {
        ".png": "image/png",
        ".jpg": "image/jpeg",
        ".jpeg": "image/jpeg",
        ".webp": "image/webp",
    }[image_path.suffix.lower()]

    response = client.models.generate_content(
        model=model,
        contents=[
            types.Part.from_bytes(data=image_bytes, mime_type=mime),
            prompt,
        ],
        config={"response_mime_type": "application/json"},
    )

    text = response.text or ""
    try:
        parsed = json.loads(text)
    except json.JSONDecodeError as e:
        raise RuntimeError(f"model returned non-JSON: {e}\n--- raw ---\n{text}\n--- end ---")

    if not isinstance(parsed, dict) or "short" not in parsed or "long" not in parsed:
        raise RuntimeError(f"model returned unexpected JSON shape: {parsed!r}")

    return {"short": parsed["short"].strip(), "long": parsed["long"].strip()}


def main():
    parser = argparse.ArgumentParser(description="Describe Civ VI art via Gemini.")
    parser.add_argument("--images", type=Path, required=True, help="Directory of image files.")
    parser.add_argument("--prompt", type=Path, required=True, help="Prompt template file.")
    parser.add_argument("--output-json", type=Path, default=None,
                        help="JSON output path (canonical). Required unless --dry-run.")
    parser.add_argument("--output-xml", type=Path, default=None,
                        help="Civ VI LOC XML output (BaseGameText format, ready to register via UpdateText).")
    parser.add_argument("--loc-prefix", default="LOC_CIVVIACCESS_VD",
                        help="LOC tag prefix; image stem + _SHORT/_LONG is appended. "
                             "Default: LOC_CIVVIACCESS_VD (visual description).")
    parser.add_argument("--model", default="gemini-2.5-flash",
                        help="Gemini model id (default: gemini-2.5-flash). Override if a newer model lands.")
    parser.add_argument("--limit", type=int, default=0,
                        help="Stop after N images this run (useful for a starter batch). 0 = all.")
    parser.add_argument("--force", action="store_true",
                        help="Re-describe even if key is already in output JSON.")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print model output to console; do NOT touch JSON or XML. "
                             "Use for prompt iteration on a single image.")
    args = parser.parse_args()

    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        print("ERROR: GEMINI_API_KEY not set in environment.", file=sys.stderr)
        sys.exit(2)

    if not args.images.is_dir():
        print(f"ERROR: --images {args.images} is not a directory.", file=sys.stderr)
        sys.exit(2)

    if not args.dry_run and args.output_json is None:
        print("ERROR: --output-json is required unless --dry-run is set.", file=sys.stderr)
        sys.exit(2)

    prompt = args.prompt.read_text(encoding="utf-8")

    from google import genai
    client = genai.Client(api_key=api_key)

    existing = load_existing(args.output_json) if args.output_json else {}

    images = sorted(
        p for p in args.images.iterdir()
        if p.is_file() and p.suffix.lower() in SUPPORTED_EXTENSIONS
    )
    if not images:
        print(f"ERROR: no supported images found in {args.images}.", file=sys.stderr)
        sys.exit(2)

    done_this_run = 0
    for image in images:
        key = image.stem
        if key in existing and not args.force:
            print(f"skip   {key} (already described)")
            continue
        if args.limit and done_this_run >= args.limit:
            print(f"stop at --limit={args.limit}")
            break
        print(f"describe {key} ...", end="", flush=True)
        t0 = time.monotonic()
        try:
            entry = describe_one(client, args.model, prompt, image)
        except Exception as e:
            print(f" FAIL ({e})")
            continue
        elapsed = time.monotonic() - t0
        if args.dry_run:
            print(f" ok ({elapsed:.1f}s, DRY RUN — not saved)")
            print(f"  short: {entry['short']}")
            print(f"  long:  {entry['long']}")
        else:
            existing[key] = entry
            write_json(args.output_json, existing)
            print(f" ok ({elapsed:.1f}s, short={len(entry['short'])} long={len(entry['long'])})")
        done_this_run += 1

    if args.dry_run:
        print("dry-run complete; JSON and XML untouched.")
        return

    if args.output_xml:
        source_note = (
            f"Visual descriptions generated from {args.images} using prompt "
            f"{args.prompt.name} on model {args.model}. {len(existing)} entries."
        )
        write_xml(args.output_xml, existing, args.loc_prefix, source_note)
        print(f"wrote XML: {args.output_xml} ({len(existing)} entries x 2 LOC rows)")

    print(f"done. described {done_this_run} this run; {len(existing)} total in {args.output_json}.")


if __name__ == "__main__":
    main()
